# Generated by Django 6.0.7 on 2026-07-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Gold', 'Gold Jewellery'), ('Silver', 'Silver Jewellery'), ('Diamond', 'Diamond Jewellery'), ('Bridal', 'Bridal Collection'), ('Custom', 'Custom Jewellery'), ('Coins', 'Gold Coins')], max_length=20)),
                ('purity', models.CharField(blank=True, choices=[('18K', '18 Karat'), ('22K', '22 Karat'), ('24K', '24 Karat')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in grams', max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new_arrival', models.BooleanField(default=False)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
