# Generated by Django 6.0.7 on 2026-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Diamond', 'Diamond')], max_length=20)),
                ('purity', models.CharField(choices=[('22K', '22K'), ('24K', '24K'), ('925', '925 Silver'), ('1CT', 'Diamond Per Carat')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=3, help_text='GST Percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='making_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Making charge in ₹', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stone_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stone/Diamond charge in ₹', max_digits=10),
        ),
    ]
