# Generated by Django 6.0.7 on 2026-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_metalrate_product_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalrate',
            name='unit',
            field=models.CharField(choices=[('10g', 'Per 10 Gram'), ('1kg', 'Per 1 Kilogram'), ('1ct', 'Per Carat')], default='10g', max_length=10),
        ),
        migrations.AlterField(
            model_name='metalrate',
            name='purity',
            field=models.CharField(choices=[('22K', '22K Gold'), ('24K', '24K Gold'), ('925', '925 Silver'), ('1CT', 'Diamond Per Carat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='metalrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Enter the current market rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='purity',
            field=models.CharField(blank=True, choices=[('18K', '18 Karat'), ('22K', '22 Karat'), ('24K', '24 Karat'), ('925', '925 Sterling Silver')], max_length=10),
        ),
    ]
