# Generated by Django 6.0.7 on 2026-08-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_making_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='making_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Making charge amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stone_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stone charge amount', max_digits=10),
        ),
    ]
