# Generated by Django 6.0.7 on 2026-08-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_product_making_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalrate',
            name='purity',
            field=models.CharField(choices=[('18K', '18K Gold'), ('22K', '22K Gold'), ('24K', '24K Gold'), ('925', '925 Silver'), ('1CT', 'Diamond Per Carat')], max_length=20),
        ),
    ]
