# Generated by Django 6.0.7 on 2026-08-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_metalrate_purity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purity', models.CharField(max_length=10, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Purity Percentage', max_digits=5)),
            ],
        ),
    ]
