# Generated by Django 6.0.7 on 2026-08-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_goldpurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metal_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Metal value before making charge, stone charge and GST', max_digits=10),
        ),
        migrations.AlterField(
            model_name='metalrate',
            name='purity',
            field=models.CharField(choices=[('24K', '24K Gold'), ('22K', '22K Gold'), ('20K', '20K Gold'), ('18K', '18K Gold'), ('14K', '14K Gold'), ('9K', '9K Gold'), ('925', '925 Silver'), ('1CT', 'Diamond Per Carat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final selling price', max_digits=10),
        ),
    ]
