# Generated by Django 6.0.7 on 2026-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_product_metal_price_alter_metalrate_purity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, choices=[('Classic', 'Classic'), ('Traditional', 'Traditional'), ('Elegant', 'Elegant'), ('Floral', 'Floral'), ('Modern', 'Modern'), ('Minimal', 'Minimal'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
