# Generated by Django 6.0.7 on 2026-08-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_product_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('jewellery_type', models.CharField(choices=[('Ring', 'Ring'), ('Necklace', 'Necklace'), ('Bridal Set', 'Bridal Set'), ('Pendant', 'Pendant'), ('Earrings', 'Earrings'), ('Couple Ring', 'Couple Ring')], max_length=50)),
                ('gold_purity', models.CharField(blank=True, max_length=20)),
                ('budget', models.CharField(blank=True, max_length=50)),
                ('design_idea', models.TextField(blank=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='custom_designs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
