# Generated by Django 6.0.7 on 2026-08-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_customenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ring', 'Ring'), ('necklace', 'Necklace'), ('bridal', 'Bridal Set'), ('pendant', 'Pendant'), ('earrings', 'Earrings'), ('couple-ring', 'Couple Ring')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='custom_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
