# Generated by Django 6.0.7 on 2026-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_customgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='making_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Making charge percentage', max_digits=5),
        ),
    ]
