# Generated by Django 6.0.7 on 2026-08-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_product_making_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_everyday',
            field=models.BooleanField(default=False),
        ),
    ]
