# Generated by Django 6.0.7 on 2026-08-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_product_is_everyday'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_designs/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Pendant', 'Pendant'), ('Necklace', 'Necklace'), ('Chain', 'Chain'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('Earrings', 'Earrings'), ('Mangalsutra', 'Mangalsutra'), ('Nose Pin', 'Nose Pin'), ('Nose Pin', 'Nose Pin'), ('Anklet', 'Anklet'), ('Jewellery Set', 'Jewellery Set'), ("Men's Jewellery", "Men's Jewellery"), ('Kids Jewellery', 'Kids Jewellery'), ('Coins', 'Coins'), ('Idols', 'Idols'), ('Utensils', 'Utensils'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
