# Generated by Django 6.0.7 on 2026-08-25 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_customdesign_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(help_text='Example: 11 Months', max_length=100)),
                ('monthly_amount', models.CharField(help_text='Example: ₹5000/month', max_length=100)),
                ('description', models.TextField()),
                ('benefits', models.TextField(help_text='Write each benefit in new line')),
                ('terms_conditions', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchemeEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.savingscheme')),
            ],
        ),
    ]
