# Generated by Django 6.0.7 on 2026-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_savingscheme_schemeenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Pendant', 'Pendant'), ('Necklace', 'Necklace'), ('Chain', 'Chain'), ('Bangles', 'Bangles'), ('Bracelet', 'Bracelet'), ('Earrings', 'Earrings'), ('Mangalsutra', 'Mangalsutra'), ('Nose Pin', 'Nose Pin'), ('Nath', 'Nath'), ('Anklet', 'Anklet'), ('Jewellery Set', 'Jewellery Set'), ("Men's Jewellery", "Men's Jewellery"), ('Kids Jewellery', 'Kids Jewellery'), ('Coins', 'Coins'), ('Idols', 'Idols'), ('Utensils', 'Utensils'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
